export const inputConfig = {
  defaultProps: {
    width: 200,
    height: 40,
    padding: 8,
    fontSize: 14,
    fontWeight: "normal",
    fontStyle: "normal",
    textAlign: "left",
    letterSpacing: 0,
    color: "#374151",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderRadius: 6,
    opacity: 100,
    boxShadow: "none",
    placeholder: "Enter text",
    value: ""
  },
  properties: [
    { key: "value",           label: "Value",          type: "text",   group: "content"    },
    { key: "placeholder",     label: "Placeholder",    type: "text",   group: "content"    },
    { key: "width",           label: "Width",          type: "number", group: "layout"     },
    { key: "height",          label: "Height",         type: "number", group: "layout"     },
    { key: "padding",         label: "Padding",        type: "number", group: "layout"     },
    { key: "fontSize",        label: "Size",           type: "number", group: "typography" },
    { key: "fontWeight",      label: "Weight",         type: "select", group: "typography", options: ["normal", "bold", "lighter", "400", "500", "600", "700"] },
    { key: "fontStyle",       label: "Style",          type: "select", group: "typography", options: ["normal", "italic", "oblique"] },
    { key: "textAlign",       label: "Align",          type: "select", group: "typography", options: ["left", "center", "right"] },
    { key: "letterSpacing",   label: "Letter Spacing", type: "number", group: "typography" },
    { key: "color",           label: "Color",          type: "color",  group: "typography" },
    { key: "backgroundColor", label: "Color",          type: "color",  group: "background" },
    { key: "borderWidth",     label: "Width",          type: "number", group: "border"     },
    { key: "borderStyle",     label: "Style",          type: "select", group: "border",     options: ["solid", "dashed", "dotted", "none"] },
    { key: "borderColor",     label: "Color",          type: "color",  group: "border"     },
    { key: "borderRadius",    label: "Radius",         type: "number", group: "border"     },
    { key: "opacity",         label: "Opacity",        type: "number", group: "effects"    },
    { key: "boxShadow",       label: "Shadow",         type: "select", group: "effects",    options: ["none", "sm", "md", "lg", "xl"] },
  ]
}
