export const buttonConfig = {
  defaultProps: {
    width: 120,
    height: 40,
    padding: 8,
    fontSize: 14,
    fontWeight: "500",
    fontStyle: "normal",
    textAlign: "center",
    letterSpacing: 0,
    textTransform: "none",
    color: "#ffffff",
    backgroundColor: "#3b82f6",
    borderWidth: 0,
    borderStyle: "solid",
    borderColor: "#2563eb",
    borderRadius: 6,
    opacity: 100,
    boxShadow: "sm",
    label: "Button",
    action: "",
  },
  properties: [
    { key: "label",           label: "Label",          type: "text",   group: "content"    },
    { key: "action",          label: "Function",       type: "text",   group: "actions"    },
    { key: "width",           label: "Width",          type: "number", group: "layout"     },
    { key: "height",          label: "Height",         type: "number", group: "layout"     },
    { key: "padding",         label: "Padding",        type: "number", group: "layout"     },
    { key: "fontSize",        label: "Size",           type: "number", group: "typography" },
    { key: "fontWeight",      label: "Weight",         type: "select", group: "typography", options: ["normal", "bold", "lighter", "400", "500", "600", "700"] },
    { key: "fontStyle",       label: "Style",          type: "select", group: "typography", options: ["normal", "italic", "oblique"] },
    { key: "textAlign",       label: "Align",          type: "select", group: "typography", options: ["left", "center", "right"] },
    { key: "letterSpacing",   label: "Letter Spacing", type: "number", group: "typography" },
    { key: "textTransform",   label: "Transform",      type: "select", group: "typography", options: ["none", "uppercase", "lowercase", "capitalize"] },
    { key: "color",           label: "Text Color",     type: "color",  group: "typography" },
    { key: "backgroundColor", label: "Color",          type: "color",  group: "background" },
    { key: "borderWidth",     label: "Width",          type: "number", group: "border"     },
    { key: "borderStyle",     label: "Style",          type: "select", group: "border",     options: ["solid", "dashed", "dotted", "none"] },
    { key: "borderColor",     label: "Color",          type: "color",  group: "border"     },
    { key: "borderRadius",    label: "Radius",         type: "number", group: "border"     },
    { key: "opacity",         label: "Opacity",        type: "number", group: "effects"    },
    { key: "boxShadow",       label: "Shadow",         type: "select", group: "effects",    options: ["none", "sm", "md", "lg", "xl"] },
  ]
}
