export const textConfig = {
  defaultProps: {
    width: 200,
    height: 40,
    padding: 8,
    fontSize: 16,
    fontWeight: "normal",
    fontStyle: "normal",
    textAlign: "left",
    letterSpacing: 0,
    color: "#000000",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderRadius: 0,
    opacity: 100,
    boxShadow: "none",
    text: "Text",
    fontFamily: "Arial, sans-serif",
    lineHeight: 1.5,
    textDecoration: "none",
    textTransform: "none"
  },
  properties: [
    { key: "width", label: "Width", type: "number", group: "layout" },
    { key: "height", label: "Height", type: "number", group: "layout" },
    { key: "padding", label: "Padding", type: "number", group: "layout" },
    { key: "fontSize", label: "Font Size", type: "number", group: "typography" },
    { key: "fontWeight", label: "Font Weight", type: "select", group: "typography", options: ["normal", "bold", "lighter", "400", "500", "600", "700"] },
    { key: "fontStyle", label: "Font Style", type: "select", group: "typography", options: ["normal", "italic", "oblique"] },
    { key: "fontFamily", label: "Font Family", type: "select", group: "typography", options: ["Arial, sans-serif", "Georgia, serif", "Courier New, monospace", "Times New Roman, serif"] },
    { key: "textAlign", label: "Text Align", type: "select", group: "typography", options: ["left", "center", "right", "justify"] },
    { key: "letterSpacing", label: "Letter Spacing", type: "number", group: "typography" },
    { key: "lineHeight", label: "Line Height", type: "number", group: "typography" },
    { key: "color", label: "Text Color", type: "color", group: "typography" },
    { key: "backgroundColor", label: "Background Color", type: "color", group: "background" },
    { key: "borderWidth", label: "Border Width", type: "number", group: "border" },
    { key: "borderStyle", label: "Border Style", type: "select", group: "border", options: ["solid", "dashed", "dotted", "none"] },
    { key: "borderColor", label: "Border Color", type: "color", group: "border" },
    { key: "borderRadius", label: "Border Radius", type: "number", group: "border" },
    { key: "opacity", label: "Opacity", type: "number", group: "effects" },
    { key: "boxShadow", label: "Box Shadow", type: "select", group: "effects", options: ["none", "sm", "md", "lg", "xl"] },
    { key: "text", label: "Text Content", type: "text", group: "content" },
    { key: "textDecoration", label: "Text Decoration", type: "select", group: "typography", options: ["none", "underline", "overline", "line-through"] },
    { key: "textTransform", label: "Text Transform", type: "select", group: "typography", options: ["none", "uppercase", "lowercase", "capitalize"] }
  ]
}