export const iconConfig = {
  defaultProps: {
    width: 48,
    height: 48,
    icon: "star",
    size: 24,
    color: "#000000",
    strokeWidth: 2,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderRadius: 8,
    padding: 8,
    opacity: 100,
    boxShadow: "none",
  },
  properties: [
    { key: "icon",        label: "Icon",         type: "iconpicker", group: "content"    },
    { key: "size",        label: "Size",         type: "number",     group: "content"    },
    { key: "color",       label: "Color",        type: "color",      group: "content"    },
    { key: "strokeWidth", label: "Stroke Width", type: "number",     group: "content"    },
    { key: "width",       label: "Width",        type: "number",     group: "layout"     },
    { key: "height",      label: "Height",       type: "number",     group: "layout"     },
    { key: "padding",     label: "Padding",      type: "number",     group: "layout"     },
    { key: "backgroundColor", label: "Background", type: "color",   group: "background" },
    { key: "borderWidth", label: "Width",        type: "number",     group: "border"     },
    { key: "borderStyle", label: "Style",        type: "select",     group: "border", options: ["solid","dashed","dotted","none"] },
    { key: "borderColor", label: "Color",        type: "color",      group: "border"     },
    { key: "borderRadius",label: "Radius",       type: "number",     group: "border"     },
    { key: "opacity",     label: "Opacity",      type: "number",     group: "effects"    },
    { key: "boxShadow",   label: "Shadow",       type: "select",     group: "effects", options: ["none","sm","md","lg","xl"] },
  ]
}