import { 
  Home, User, Search, Heart, Star, Settings, 
  Mail, Phone, Camera, Music, Video, Map,
  Bell, Bookmark, Calendar, Clock, Cloud,
  Code, Coffee, Download, Edit, Eye,
  File, Folder, Globe, Image, Info,
  Key, Link, Lock, Menu, Message,
  Moon, Package, Play, Plus, Power,
  Printer, RefreshCw, Save, Send, Share,
  Shield, ShoppingCart, Sun, Trash, Upload,
  Wifi, X, Zap, AlertCircle, Check,
  ChevronDown, ChevronUp, ChevronLeft, ChevronRight,
  ArrowLeft, ArrowRight, ArrowUp, ArrowDown,
  ThumbsUp, ThumbsDown, Flag, Tag, Tool
} from "lucide-react"

export const iconList = [
  { name: "home", icon: Home },
  { name: "user", icon: User },
  { name: "search", icon: Search },
  { name: "heart", icon: Heart },
  { name: "star", icon: Star },
  { name: "settings", icon: Settings },
  { name: "mail", icon: Mail },
  { name: "phone", icon: Phone },
  { name: "camera", icon: Camera },
  { name: "music", icon: Music },
  { name: "video", icon: Video },
  { name: "map", icon: Map },
  { name: "bell", icon: Bell },
  { name: "bookmark", icon: Bookmark },
  { name: "calendar", icon: Calendar },
  { name: "clock", icon: Clock },
  { name: "cloud", icon: Cloud },
  { name: "code", icon: Code },
  { name: "coffee", icon: Coffee },
  { name: "download", icon: Download },
  { name: "edit", icon: Edit },
  { name: "eye", icon: Eye },
  { name: "file", icon: File },
  { name: "folder", icon: Folder },
  { name: "globe", icon: Globe },
  { name: "image", icon: Image },
  { name: "info", icon: Info },
  { name: "key", icon: Key },
  { name: "link", icon: Link },
  { name: "lock", icon: Lock },
  { name: "menu", icon: Menu },
  { name: "moon", icon: Moon },
  { name: "package", icon: Package },
  { name: "play", icon: Play },
  { name: "plus", icon: Plus },
  { name: "power", icon: Power },
  { name: "save", icon: Save },
  { name: "send", icon: Send },
  { name: "share", icon: Share },
  { name: "shield", icon: Shield },
  { name: "cart", icon: ShoppingCart },
  { name: "sun", icon: Sun },
  { name: "trash", icon: Trash },
  { name: "upload", icon: Upload },
  { name: "wifi", icon: Wifi },
  { name: "zap", icon: Zap },
  { name: "check", icon: Check },
  { name: "x", icon: X },
  { name: "alert", icon: AlertCircle },
  { name: "thumbsup", icon: ThumbsUp },
  { name: "thumbsdown", icon: ThumbsDown },
  { name: "flag", icon: Flag },
  { name: "tag", icon: Tag },
  { name: "arrowleft", icon: ArrowLeft },
  { name: "arrowright", icon: ArrowRight },
  { name: "arrowup", icon: ArrowUp },
  { name: "arrowdown", icon: ArrowDown },
]